GET http://localhost:8081/spring-app/test/test1?i=0

###

POST http://localhost:8081/spring-app/book/findAll
Content-Type: application/json

{
    "id": "123456",
    "name": "it",
    "release": "2015-06-01 12:25:24"
}

###

GET http://localhost:8081/spring-app/book/page

###

GET http://localhost:8081/spring-app/book/test

###


GET http://localhost:8081/spring-app/book/prop

###

POST http://localhost:8081/spring-app/book/save
Content-Type: application/json

{
    "id": "12345679",
    "author": "mark",
    "name": "abc",
    "version": 0
}

###

POST http://localhost:8081/spring-app/user/save
Content-Type: application/json

{
    "name": "yee"
}

###

GET http://localhost:8081/spring-app/user/list

###

