spring:
  application:
    name: gateway
  profiles:
    active: dev
    group:
      dev: dev
      prod: prod
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  pid:
    file: ./log/${spring.application.name}.pid

logging:
  file:
    name: ./log/${spring.application.name}.log