server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}

spring:
  cloud:
    gateway:
      routes:

        - id: service1
          order: 2
          predicates:
            - Path=${server.servlet.context-path}/service1/**
          filters:
            - PreserveHostHeader
            - RewritePath=${server.servlet.context-path}/service1/?(?<segment>.*), /service1/$\{segment}
            - Authentication
          uri: http://localhost:8081

        - id: service2
          predicates:
            - Path=${server.servlet.context-path}/service2/**
          filters:
            - PreserveHostHeader
            - RewritePath=${server.servlet.context-path}/service2/?(?<segment>.*), /service2/$\{segment}
            - Authentication
          uri: http://localhost:8082

        - id: login
          order: 1
          predicates:
            - Path=${server.servlet.context-path}/service1/test/login
          filters:
            - PreserveHostHeader
            - RewritePath=${server.servlet.context-path}/service1/?(?<segment>.*), /service1/$\{segment}
          uri: http://localhost:8081
