server:
  port: 8081

spring:
  datasource:
    username: dev
    password: AES[fJkm+OidsnWVG+SjLiHXrQ==]
    url: jdbc:h2:./db/test;AUTO_SERVER=TRUE
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
