server:
  port: 8081
  servlet:
    context-path: /${spring.application.name}

spring:
  datasource:
    username: dev
    password: AES[fJkm+OidsnWVG+SjLiHXrQ==]
    url: jdbc:mysql://localhost:3306/test
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

multi-datasource:
  enable: false
  routes:
    - key: DB1
      username: dev
      password: AES[fJkm+OidsnWVG+SjLiHXrQ==]
      url: jdbc:mysql://localhost:3307/test
    - key: DB2
      username: dev
      password: AES[fJkm+OidsnWVG+SjLiHXrQ==]
      url: jdbc:postgresql://localhost:5432/test