server:
  port: 8081

spring:
  datasource:
    username: dev
    password: AES[fJkm+OidsnWVG+SjLiHXrQ==]
    url: jdbc:mysql://localhost:3306/test
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

