spring:
  application:
    name: spring-app
  profiles:
    active: dev
    group:
      dev: dev, devAppend
      prod: prod
    include: custom
  jackson:
    dateformat: yyyy-MM-dd HH:mm:ss
    timezone: GMT+8
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  pid:
    file: ./log/${spring.application.name}.pid
  jpa:
    open-in-view: true

logging:
  file:
    name: ./log/${spring.application.name}.log

