spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    # jdbcTemplate log sql
    org.springframework.jdbc.core.JdbcTemplate: TRACE
    # jdbcTemplate log params
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    # jpa log params
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE